Create python_win10.md
nnstu-appmath/python pull request #13
Opened 2023-03-14 19:07 UTC by 21-Andrey-PM

2023-03-15 13:19 UTC, gamehunt commented on python_win10.md
> +1. Запустите командую строку
Стоит отметить, что если консоль была открыта до установки питона, то её надо открыть заного, чтобы подцепилась новая запись в PATH

2023-03-15 13:24 UTC, gamehunt commented on python_win10.md
> +```
Тут съехал отступ для второго хука + есть лишний пробел вначале, по итогу yaml не валидный, если его копировать как есть. Поправил форматирование через линтер.
 
```suggestion
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --strict-optional]  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
```

2023-03-15 13:28 UTC, gamehunt requested changes
.

2023-03-17 14:16 UTC, arybin93 requested changes
Ок, спасибо, оставил пару комментариев, хорошо бы поправить

2023-03-17 14:16 UTC, arybin93 commented on python_win10.md
> +- Пишем и запускаем: `Set-ExecutionPolicy RemoteSigned`
Полная команда вроде такая `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`?

2023-03-17 14:16 UTC, arybin93 commented on python_win10.md
> +Введите команду `pre-commit run --all-files` и нажмите `enter` для запуска всех `pre-commit` хуков, указанных в файле конфигурации.
Да, так же можно отметить, что репозиторий должен быть уже создан/склонирован

2023-03-28 09:55 UTC, gamehunt approved these changes

2023-03-31 12:57 UTC, arybin93 approved these changes
👍 Можешь мёржить и занести себе баллы за работу, спасибо!

2023-04-01 06:32 UTC, merged