3_python_data_types_operators_cycles_conditions
nnstu-appmath/python pull request #7
Opened 2022-11-04 19:05 UTC by IrinaDogadina

2022-11-04 20:25 UTC, dashakotova0702 requested changes
Мои пожелания и предложения for this tutorial

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +Остаток от деления | % |
Есть еще: -x, abs(x), pow(x,y) - второй вариант возведения в степень.

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +    False
Можно делать двойные неравенства/равенства без and, or
```
>>> a = 4
>>> 3 < a < 5
True
```

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> + Чаще всего данные операторы используются для написания условий в циклах. Рассмотрим какие циклы бывают в python.
Может тут начать новую тему "Циклы"?

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +#While
И соответственно каждый цикл это будет подтема с меньшим заголовком

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> + Циклы в Python позволяют сделать из сложных задач более простые. С помощью них вы можете выполнять действие многократно, не плодя код выполнения этих дйествий.
Тут очепятка "действий"

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +Разберем пример чуть более подробно. После ключевого слова while следует блок с условием для выхода из цикла, после знака : следуют выражения, которые будут выполнятьтся с каждым заходом в цикл. При
Тут тоже очепятка "выполняться"

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +Разберем пример чуть более подробно. После ключевого слова while следует блок с условием для выхода из цикла, после знака : следуют выражения, которые будут выполнятьтся с каждым заходом в цикл. При
Стоит сказать, что телом цикла считается только то, что написано после 4 пробелов или одной табуляции

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +Разберем пример чуть более подробно. После ключевого слова for следует блок с условием для выхода из цикла, после знака : следуют выражения, которые будут выполнятьтся с каждым заходом в цикл. Услови
Тут не очень понятен синтаксис for. Наверное, лучше сказать, что после ключевого слово for следует переменная, отвечающая за итерации, далее ключевое слово in, а в конце объект, по которому пройдется цикл.

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +Если необходимо исполнить ряд инструкций в которых соблюдаются определенные условия, то необходимо использовать условные операторы.
Тут наверное надо сделать заголовок темы "Условные операторы", а сами эти операторы рассматривать как подтемы

2022-11-04 20:25 UTC, dashakotova0702 commented on python_guide_2.md
> +       statement
Хочется примерчиков на эти условные операторы

2022-11-07 17:05 UTC, arybin93 requested changes
В целом, направление верное, надо учесть оставленные комментарии

2022-11-07 17:05 UTC, arybin93 commented on python_guide_2.md
> + Думаю, что такие простые типы как int, float, str не нуждаются в объяснении, а типы list, tuple, complex, range рассмотрим на примерах.
Хорошо бы ещё про dict добавить, что думаете?

2022-11-07 17:05 UTC, arybin93 commented on python_guide_2.md
> +
Дать понятие immutable и mutable тоже хорошо бы

2022-11-08 06:59 UTC, RuslanShamshetdinov commented on python_guide_2.md
> +Задается кортеж из строки, каждая его буква будет являтся элементом кортежа
Согласен, что хотелось бы более подробной информации про кортеж.

2022-11-08 11:44 UTC, RuslanShamshetdinov commented
В принципе, после прочтения этой документации и комментариев Даши и Артема я даже не знаю, что можно еще добавить. Мне как новичку в питоне "гайд" понравился, написано хорошо. Буду ждать обновленной версии с исправленными замечаниями и тогда возможно появятся идеи.

2022-11-08 11:46 UTC, RuslanShamshetdinov reviewed
В принципе, после прочтения этой документации и комментариев Даши и Артема я даже не знаю, что можно еще добавить. Мне как новичку в питоне "гайд" понравился, написано хорошо. Буду ждать обновленной версии с исправленными замечаниями и тогда возможно появятся идеи.

2022-11-09 17:01 UTC, arybin93 approved these changes
По мне стало лучше, спасибо)
Может ещё Руслан, на что-то обратит внимание.

2022-11-09 18:04 UTC, dashakotova0702 approved these changes
Типы данных стали визуально понятнее и структурированнее, по остальному тоже вопросов нет)

2022-11-10 15:24 UTC, RuslanShamshetdinov approved these changes

2022-11-10 15:27 UTC, merged